#cloud-config
package_upgrade: true
write_files:
  - path: /opt/nat/conf/main-interface
    permissions: '0755'
    content: ${main_interface}
  - path: /opt/nat/snat.sh
    permissions: '0755'
    content: |
      # wait for eth1
      while ! ip link show dev eth1; do
        sleep 1
      done

      main_interface=$(cat /opt/nat/conf/main-interface)

      sysctl -q -w net.ipv4.conf.all.rp_filter=0
      sysctl -q -w net.ipv4.conf.eth0.rp_filter=0
      sysctl -q -w net.ipv4.conf.eth1.rp_filter=0
      sysctl -q -w net.ipv4.conf.default.rp_filter=0

      # enable IP forwarding and NAT
      sysctl -q -w net.ipv4.ip_forward=1
      sysctl -q -w net.ipv4.conf.eth1.send_redirects=0
      iptables -t nat -A POSTROUTING -o $main_interface -j MASQUERADE

      if [ "$main_interface" == "eth1" ]; then
        # switch the default route to eth1
        ip route del default dev eth0
      fi

      # wait for network connection
      curl --retry 10 "http://www.example.com" > /tmp/curl-nat-test.log

      # reestablish connections
      systemctl restart amazon-ssm-agent.service
  - path: /etc/systemd/system/snat.service
    content: |
      [Unit]
      Description = SNAT via ENI eth1
      After=network.target
      StartLimitIntervalSec=0
      StartLimitBurst=5
      StartLimitIntervalSec=60

      [Service]
      ExecStart = /bin/bash -c "/opt/nat/snat.sh" 2>&1 > /tmp/snat.logs
      Type = simple
      Restart=on-failure
      RestartSec=5

      [Install]
      WantedBy = multi-user.target
